spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  server:
    renewal-percent-threshold: 0.49
    enableSelfPreservation: false
  instance:
    hostname: localhost
    appname: eureka
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/