spring:
  application:
    name: user-service
server:
  port: ${random.int[9000,9999]}
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true               
    waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/